---
- name: remove default vhost
  command: rabbitmqctl delete_vhost /
  when:
    - rabbitmq_vhost != '/'

- name: remove guest user
  command: rabbitmqctl delete_user guest
  when: "'guest' in rabbitmq_users.stdout"
