---
- name: enable rabbitmq management
  command: rabbitmq-plugins enable rabbitmq_management
  notify: restart rabbitmq

- name: restart rabbitmq
  service:
    name: "{{ item }}"
    state: restarted
  with_items: "{{ rabbitmq_service_names | default(rabbitmq_service_names_default) }}"

- name: remove default vhost
  command: rabbitmqctl delete_vhost /
  when:
    - rabbitmq_vhost != '/'

- name: remove guest user
  command: "rabbitmqctl delete_user guest"
  when: "'guest' in rabbitmq_users.stdout"
