---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu
    image: solita/ubuntu-systemd:latest
    privileged: True
    command: /sbin/init
    volumes:
      - "molecule_user/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  inventory:
    host_vars:
      ubuntu:
        rabbitmq_vhost: molecule_vhost
        rabbitmq_user_name: molecule_user
        rabbitmq_user_pass: molecule_pass
        rabbitmq_user_perm_conf: 'conf'
        rabbitmq_user_perm_write: 'write'
        rabbitmq_user_perm_read: 'read'
scenario:
  name: vhost
verifier:
  name: testinfra
  lint:
    name: flake8
